apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "microservices-ip"
spec:
  rules:
  - http:
      paths:
      - path: /patients
        pathType: Prefix
        backend:
          service:
            name: patient-service
            port:
              number: 80
      - path: /appointments
        pathType: Prefix
        backend:
          service:
            name: application-service
            port:
              number: 80
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 80
